FROM python:3.10.19

WORKDIR /app

COPY bge/requirements.txt .
RUN pip install -r requirements.txt
COPY bge/reranker.py .
COPY protos/bge_rerank.proto ./protos/bge_rerank.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. protos/bge_rerank.proto


CMD ["python", "reranker.py"]