FROM python:3.10.19

WORKDIR /app

COPY bge/requirements.txt .
RUN pip install -r requirements.txt
COPY bge/embeder.py .
COPY protos/bge_embed.proto ./protos/bge_embed.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. protos/bge_embed.proto

CMD ["python", "embeder.py"]