# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/protos/bge_rerank.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/protos/bge_rerank.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n services/protos/bge_rerank.proto\"1\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x03(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\" \n\x0eRerankResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x32\x36\n\tBgeRerank\x12)\n\x06Rerank\x12\x0e.RerankRequest\x1a\x0f.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.protos.bge_rerank_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RERANKREQUEST']._serialized_start=36
  _globals['_RERANKREQUEST']._serialized_end=85
  _globals['_RERANKRESPONSE']._serialized_start=87
  _globals['_RERANKRESPONSE']._serialized_end=119
  _globals['_BGERERANK']._serialized_start=121
  _globals['_BGERERANK']._serialized_end=175
# @@protoc_insertion_point(module_scope)
