# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/protos/bge_embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/protos/bge_embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fservices/protos/bge_embed.proto\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"-\n\rEmbedResponse\x12\x1c\n\x07vectors\x18\x01 \x03(\x0b\x32\x0b.VectorData\"s\n\nVectorData\x12\r\n\x05\x64\x65nse\x18\x01 \x03(\x02\x12\'\n\x06sparse\x18\x02 \x03(\x0b\x32\x17.VectorData.SparseEntry\x1a-\n\x0bSparseEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x32\n\x08\x42geEmbed\x12&\n\x05\x45mbed\x12\r.EmbedRequest\x1a\x0e.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.protos.bge_embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORDATA_SPARSEENTRY']._loaded_options = None
  _globals['_VECTORDATA_SPARSEENTRY']._serialized_options = b'8\001'
  _globals['_EMBEDREQUEST']._serialized_start=35
  _globals['_EMBEDREQUEST']._serialized_end=64
  _globals['_EMBEDRESPONSE']._serialized_start=66
  _globals['_EMBEDRESPONSE']._serialized_end=111
  _globals['_VECTORDATA']._serialized_start=113
  _globals['_VECTORDATA']._serialized_end=228
  _globals['_VECTORDATA_SPARSEENTRY']._serialized_start=183
  _globals['_VECTORDATA_SPARSEENTRY']._serialized_end=228
  _globals['_BGEEMBED']._serialized_start=230
  _globals['_BGEEMBED']._serialized_end=280
# @@protoc_insertion_point(module_scope)
